server: server-iterative.cpp
	g++ -Wall -Wextra -g3 server-iterative.cpp -o server

server-io-multiplexing-skeleton: server-io-multiplexing-skeleton.cpp
	g++ -Wall -Wextra -g3 server-io-multiplexing-skeleton.cpp -o server-io-multiplexing-skeleton

client-simple: client-simple.cpp
	g++ -Wall -Wextra -g3 client-simple.cpp -o client-simple

client-multi: client-multi.cpp
	g++ -Wall -Wextra -g3 client-multi.cpp -o client-multi

.PHONY: clean
clean:
	rm -f server
	rm -f server-io-multiplexing-skeleton
	rm -f client-simple
	rm -f client-multi
