server: server-iterative.cpp
	g++ -Wall -Wextra -g3 server-iterative.cpp -o server

client-simple: client-simple.cpp
	g++ -Wall -Wextra -g3 client-simple.cpp -o client-simple

client-multi: client-multi.cpp
	g++ -Wall -Wextra -g3 client-multi.cpp -o client-multi

.PHONY: clean
clean:
	rm -f server
	rm -f client-simple
	rm -f client-multi
